version: "3.8"

services:

  app:
    restart: always
    build: .
    command: sh -c "alembic revision --autogenerate && alembic upgrade head && uvicorn app:app --reload --host 0.0.0.0"
    container_name: fastapi-app
    ports:
      - '8001:8000'
    environment:
      - DATABASE_URL=postgresql://blog:blog@postgres-db:5432/blog
      - DATABASE_ASYNC_URL=postgresql+asyncpg://blog:blog@postgres-db:5432/blog
    logging:
      options:
        max-size: '25M'
        max-file: '5'
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:15-alpine3.18
    container_name: postgres-db
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=blog
      - POSTGRES_USER=blog
      - POSTGRES_DB=blog
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always