version: "3.8"

services:

  app:
    build: .
    command: sh -c "alembic revision --autogenerate && alembic upgrade head && gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --proxy-headers --forwarded-allow-ips="*""
#    command: sh -c "alembic revision --autogenerate && alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000 --reload --proxy-headers --forwarded-allow-ips="*""
    container_name: fastapi-app
    ports:
      - '8010:8000'
    environment:
      - DB_URL=postgresql://blog:blog@postgres-db:5432/blog
      - DB_ASYNC_URL=postgresql+asyncpg://blog:blog@postgres-db:5432/blog
      - SECRET_KEY=supVop-key-secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=500
    logging:
      options:
        max-size: '25M'
        max-file: '5'
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: always

  postgres:
    image: postgres:15-alpine3.18
    container_name: postgres-db
    #hostname: postgres
    environment:
      - POSTGRES_PASSWORD=blog
      - POSTGRES_USER=blog
      - POSTGRES_DB=blog
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always

  redis:
    image: redis:7.0.4-alpine
    container_name: redis-cache
    hostname: redis